# https://coverage.readthedocs.io/en/latest/config.html
[tool.coverage.run]
# some workarounds for source and test files being intermingled, not all using modules, etc.
source = [
  "examples/",
  "examples/flask/",
  "tests/"
]
