# adapted from
# https://docs.cloud.google.com/storage/docs/samples/storage-remote-terraform-backend-template

resource "google_storage_bucket" "backend" {
  name     = "sipa-advanced-computing-tf-backend"
  location = "US"

  force_destroy               = false
  public_access_prevention    = "enforced"
  uniform_bucket_level_access = true

  versioning {
    enabled = true
  }
}

resource "local_file" "backend" {
  file_permission = "0644"
  filename        = "${path.module}/backend.tf"

  content = <<-EOT
  # generated by bucket_backend.tf - don't modify directly

  terraform {
    backend "gcs" {
      bucket = "${google_storage_bucket.backend.name}"
    }
  }
  EOT
}
